version: '3.8'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: home
      POSTGRES_PASSWORD: home
      POSTGRES_DB: home
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: